# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 05:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainSection', '0002_auto_20171026_0216'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='select',
            field=models.CharField(choices=[('장고', '장고'), ('자스', '자스'), ('제이쿼리', '제이쿼리'), ('django', 'django')], default='장고', max_length=50),
            preserve_default=False,
        ),
    ]
